//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmployeeID { get; set; }
        public int UserDataID { get; set; }
        public int ManagerID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Position { get; set; }
        public Nullable<int> SectorID { get; set; }
        public string ProfessionalQualificationsLevel { get; set; }
        public Nullable<int> YearsOfService { get; set; }
    
        public virtual tblManager tblManager { get; set; }
        public virtual tblSector tblSector { get; set; }
        public virtual tblUserData tblUserData { get; set; }
    }
}
