//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserData()
        {
            this.tblAdministrators = new HashSet<tblAdministrator>();
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblManagers = new HashSet<tblManager>();
        }
    
        public int UserDataID { get; set; }
        public string GivenName { get; set; }
        public string Surname { get; set; }
        public string PersonalNo { get; set; }
        public string Sex { get; set; }
        public string PlaceOfResidence { get; set; }
        public string MaritalStatus { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdministrator> tblAdministrators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblManager> tblManagers { get; set; }
    }
}
