//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAdministrator
    {
        public string Administrator_Name { get; set; }
        public string PersonalNo { get; set; }
        public string Sex { get; set; }
        public string PlaceOfResidence { get; set; }
        public string MaritalStatus { get; set; }
        public int UserDataID { get; set; }
        public int AdministratorID { get; set; }
        public System.DateTime ExpirationAccountDate { get; set; }
        public string AdministratorTeam { get; set; }
    }
}
