//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwManager
    {
        public string Administrator_Name { get; set; }
        public string PersonalNo { get; set; }
        public string Sex { get; set; }
        public string PlaceOfResidence { get; set; }
        public string MaritalStatus { get; set; }
        public int UserDataID { get; set; }
        public Nullable<int> LevelOfResponsibility { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Email { get; set; }
        public string OfficeNumber { get; set; }
        public string ProjectsCount { get; set; }
    }
}
